# Generated by Django 3.1.2 on 2021-08-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
