# Generated by Django 3.1.2 on 2021-08-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender_app', '0002_auto_20210826_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
