# Generated by Django 3.1.2 on 2021-08-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender_app', '0003_auto_20210826_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
