# Generated by Django 3.1.2 on 2021-09-30 05:02

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='logo',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(base_url='form.urlsmedia/', collection='event'), upload_to=''),
        ),
    ]
